{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-oidc-proxy
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.tls.secretName }}
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - kube-oidc-proxy
    - kube-oidc-proxy.{{ .Release.Namespace }}
    - kube-oidc-proxy.{{ .Release.Namespace }}.svc
    - kube-oidc-proxy.{{ .Release.Namespace }}.svc.cluster.local
    - k8s-api.localhost
{{- end }}
