apiVersion: v2
name: headlamp
description: Headlamp - Kubernetes Dashboard with OIDC auth
version: 0.1.0
appVersion: "0.39.0"
dependencies:
  - name: headlamp
    version: "0.39.0"
    repository: "https://kubernetes-sigs.github.io/headlamp/"
