{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: strimzi-cluster-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: strimzi-cluster-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
{{- end }}
