apiVersion: v2
name: trust-manager
description: cert-manager trust-manager for CA bundle distribution
type: application
version: 0.1.0
appVersion: "0.14.0"
dependencies:
  - name: trust-manager
    version: "0.14.0"
    repository: "https://charts.jetstack.io"
