{{- if .Values.server.seal.transit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-transit-token
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # VAULT_TRANSIT_SEAL_TOKEN is auto-read by Vault for transit seal auth
  VAULT_TRANSIT_SEAL_TOKEN: {{ .Values.server.seal.transit.token | b64enc | quote }}
{{- end }}
