apiVersion: v1
kind: Service
metadata:
  name: zot-registry-cache
spec:
  ports:
    - port: {{ .Values.ports.zot }}
      targetPort: {{ .Values.ports.zot }}
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: zot-registry-cache
subsets:
  - addresses:
      - ip: {{ .Values.cacheRegistryIP }}
    ports:
      - port: {{ .Values.ports.zot }}
        protocol: TCP
