apiVersion: v1
kind: Service
metadata:
  name: zot-registry-cache
spec:
  ports:
    - port: {{ .Values.ports.zot }}
      targetPort: {{ .Values.ports.zot }}
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: zot-registry-cache
  labels:
    kubernetes.io/service-name: zot-registry-cache
addressType: IPv4
ports:
  - port: {{ .Values.ports.zot }}
    protocol: TCP
endpoints:
  - addresses:
      - {{ .Values.cacheRegistryIP }}
