apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tetragon-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: tetragon-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tetragon-operator
      app.kubernetes.io/component: operator
  endpoints:
    - port: metrics
      interval: 10s
      path: /metrics
