apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- with .tls }}
      tls:
        mode: {{ .mode }}
        certificateRefs:
          {{- toYaml .certificateRefs | nindent 10 }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: {{ .allowedRoutes.namespaces.from }}
    {{- end }}
