apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayApi.gatewayClass.name }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.gatewayApi.gatewayClass.controllerName }}
