apiVersion: v2
name: monitoring
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: "68.2.2"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: loki
    version: "6.23.0"
    repository: "https://grafana.github.io/helm-charts"
  - name: alloy
    version: "1.5.1"
    repository: "https://grafana.github.io/helm-charts"
