apiVersion: v2
name: vault
description: HashiCorp Vault for Kubernetes secrets management
version: 1.0.0
dependencies:
  - name: vault
    version: "0.31.0"
    repository: "https://helm.releases.hashicorp.com"
