---
# Allow egress to Kubernetes API server
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-k8s-api-egress
  namespace: sealed-secrets
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "{{ .Values.ports.apiServerSecure }}"
              protocol: TCP
        - ports:
            - port: "{{ .Values.ports.apiServer }}"
              protocol: TCP
---
# Allow ingress for sealed-secrets controller (for kubeseal CLI and webhook)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-controller-ingress
  namespace: sealed-secrets
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: sealed-secrets
  ingress:
    - fromEntities:
        - kube-apiserver
        - remote-node
        - host
      toPorts:
        - ports:
            - port: "{{ .Values.ports.sealedSecretsController }}"
              protocol: TCP
