---
# Default deny all ingress and egress
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector: {}
  # Empty arrays mean deny all
  ingress: []
  egress: []
