---
# AlertManager network policy - ingress and egress
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  ingress:
    # Allow from Prometheus
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.alertmanager.http }}"
            - port: "{{ .Values.ports.alertmanager.web }}"
    # Allow from Grafana
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana
      toPorts:
        - ports:
            - port: "{{ .Values.ports.alertmanager.http }}"
    # Allow mesh communication between AlertManager instances
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: alertmanager
      toPorts:
        - ports:
            - port: "{{ .Values.ports.alertmanager.http }}"
            - port: "{{ .Values.ports.alertmanager.cluster }}"
  egress:
    # Allow mesh communication between AlertManager instances
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: alertmanager
      toPorts:
        - ports:
            - port: "{{ .Values.ports.alertmanager.http }}"
            - port: "{{ .Values.ports.alertmanager.cluster }}"
