---
# Alloy Consumer network policy - ingress and egress
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: alloy-consumer
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: alloy-consumer
  ingress:
    # Allow metrics scraping from Prometheus
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.alloy.http }}"
              protocol: TCP
  egress:
    # Allow consuming logs from Kafka brokers
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kafka
      toPorts:
        - ports:
            - port: "{{ .Values.ports.kafka.broker.plain }}"
              protocol: TCP
    # Allow sending logs to Loki Gateway
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: "{{ .Values.ports.loki.gateway }}"
              protocol: TCP
    # Allow DNS resolution
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "{{ .Values.ports.dns }}"
              protocol: UDP
            - port: "{{ .Values.ports.dns }}"
              protocol: TCP
