---
# Grafana network policy - ingress and egress
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  ingress:
    # Allow from Gateway (Cilium Envoy) - connects directly to pod port 3000
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "{{ .Values.ports.grafana }}"
              protocol: TCP
    # Allow from host for port-forwarding
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "{{ .Values.ports.grafana }}"
              protocol: TCP
    # Allow from Prometheus for scraping Grafana metrics
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.grafana }}"
              protocol: TCP
  egress:
    # Allow DNS resolution
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
    # Allow API server access (for Kubernetes data source plugin)
    - toEntities:
        - kube-apiserver
    # Allow querying Prometheus
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.prometheus }}"
    # Allow querying AlertManager
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: alertmanager
      toPorts:
        - ports:
            - port: "{{ .Values.ports.alertmanager.http }}"
    # Allow querying Loki Gateway
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: "{{ .Values.ports.loki.gateway }}"
    # Allow querying Tempo
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: tempo
      toPorts:
        - ports:
            - port: "{{ .Values.ports.tempo.http }}"
              protocol: TCP
    # Allow downloading dashboards from grafana.com (for init container)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "{{ .Values.ports.gateway.https }}"
              protocol: TCP
