---
# Loki Canary network policy - ingress and egress
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-canary
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: canary
  ingress:
    # Allow Prometheus to scrape metrics
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.loki.canary }}"
              protocol: TCP
  egress:
    # Allow sending logs to Loki Gateway
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: "{{ .Values.ports.loki.gateway }}"
              protocol: TCP
