---
# Allow Loki memcached chunks cache ingress from single-binary
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-memcached-chunks-ingress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: memcached-chunks-cache
  ingress:
    # Allow from Loki single-binary
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: single-binary
      toPorts:
        - ports:
            - port: "11211"
              protocol: TCP
    # Allow Prometheus to scrape metrics
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "9150"
              protocol: TCP
---
# Allow Loki memcached chunks cache egress for DNS
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-memcached-chunks-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: memcached-chunks-cache
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
---
# Allow Loki memcached results cache ingress from single-binary
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-memcached-results-ingress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: memcached-results-cache
  ingress:
    # Allow from Loki single-binary
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: single-binary
      toPorts:
        - ports:
            - port: "11211"
              protocol: TCP
    # Allow Prometheus to scrape metrics
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "9150"
              protocol: TCP
---
# Allow Loki memcached results cache egress for DNS
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-memcached-results-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: memcached-results-cache
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
