---
# Allow Loki Canary ingress from Prometheus
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-canary-ingress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: canary
  ingress:
    # Allow Prometheus to scrape metrics
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.loki.canary }}"
              protocol: TCP
---
# Allow Loki Canary egress to Gateway and DNS
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-canary-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: canary
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "{{ .Values.ports.dns }}"
              protocol: UDP
    # Allow sending logs to Loki Gateway
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: "{{ .Values.ports.loki.gateway }}"
              protocol: TCP
