---
# Prometheus operator network policy - egress only
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-operator
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
  egress:
    # Allow API server access
    - toEntities:
        - kube-apiserver
---
# Admission webhook patch job network policy - egress only
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: admission-patch
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kube-prometheus-stack-admission-patch
  egress:
    # Allow API server access
    - toEntities:
        - kube-apiserver
