---
# Prometheus operator network policy - egress only
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-operator
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
  egress:
    # Allow API server access
    - toEntities:
        - kube-apiserver
---
# Admission webhook deployment network policy
# The webhook validates PrometheusRule resources and needs API server access
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: admission-webhook
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: kube-prometheus-stack-operator-webhook
  ingress:
    # Allow webhook calls from kube-apiserver
    - fromEntities:
        - kube-apiserver
  egress:
    # Allow API server access for lookups
    - toEntities:
        - kube-apiserver
