---
# Prometheus network policy - ingress and egress
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  ingress:
    # Allow from Grafana
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana
      toPorts:
        - ports:
            - port: "{{ .Values.ports.prometheus }}"
    # Allow from Prometheus (for federation)
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.prometheus }}"
  egress:
    # Allow API server access
    - toEntities:
        - kube-apiserver
    # Allow scraping metrics from all pods in monitoring namespace
    - toEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "{{ .Values.ports.prometheus }}"
            - port: "{{ .Values.ports.kubeStateMetrics }}"
            - port: "{{ .Values.ports.loki.gateway }}"
            - port: "{{ .Values.ports.alertmanager.http }}"
            - port: "{{ .Values.ports.grafana }}"
            - port: "{{ .Values.ports.loki.http }}"
            - port: "{{ .Values.ports.tempo.http }}"
            - port: "{{ .Values.ports.loki.canary }}"
            - port: "{{ .Values.ports.memcached.exporter }}"
            - port: "{{ .Values.ports.prometheusOperatorWebhook }}"
            - port: "{{ .Values.ports.alloy.http }}"
    # Allow scraping metrics from kube-system namespace (Cilium, Hubble, Tetragon, CoreDNS)
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "{{ .Values.ports.ciliumAgent }}"
            - port: "{{ .Values.ports.ciliumOperator }}"
            - port: "{{ .Values.ports.hubble }}"
            - port: "{{ .Values.ports.hubbleRelay }}"
            - port: "{{ .Values.ports.hubbleRelayGrpc }}"
            - port: "{{ .Values.ports.envoy }}"
            - port: "{{ .Values.ports.tetragon }}"
            - port: "{{ .Values.ports.tetragonOperator }}"
            - port: "{{ .Values.ports.ingressMetrics }}"
            - port: "{{ .Values.ports.coreDns }}"
    # Allow scraping metrics from kyverno namespace
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kyverno
      toPorts:
        - ports:
            - port: "{{ .Values.ports.kyverno.metrics }}"
    # Allow scraping metrics from kafka namespace
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kafka
      toPorts:
        - ports:
            - port: "{{ .Values.ports.kafka.jmxMetrics }}"
            - port: "{{ .Values.ports.kafka.exporter }}"
            - port: "{{ .Values.ports.strimziOperator.metrics }}"
    # Allow scraping metrics from strimzi-system namespace
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: strimzi-system
      toPorts:
        - ports:
            - port: "{{ .Values.ports.strimziOperator.metrics }}"
    # Allow scraping metrics from argocd namespace
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: argocd
      toPorts:
        - ports:
            - port: "{{ .Values.ports.argocd.metrics.server }}"
            - port: "{{ .Values.ports.argocd.metrics.repoServer }}"
            - port: "{{ .Values.ports.argocd.metrics.controller }}"
            - port: "{{ .Values.ports.argocd.metrics.applicationset }}"
    # Allow scraping metrics from trivy-system namespace
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: trivy-system
      toPorts:
        - ports:
            - port: "{{ .Values.ports.trivyOperator.metrics }}"
    # Allow scraping metrics from host network (Cilium, Tetragon components on nodes)
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "{{ .Values.ports.ciliumAgent }}"
            - port: "{{ .Values.ports.ciliumOperator }}"
            - port: "{{ .Values.ports.hubble }}"
            - port: "{{ .Values.ports.hubbleRelay }}"
            - port: "{{ .Values.ports.kubelet }}"
            - port: "{{ .Values.ports.hubbleRelayGrpc }}"
            - port: "{{ .Values.ports.tetragon }}"
            - port: "{{ .Values.ports.tetragonOperator }}"
            - port: "{{ .Values.ports.nodeExporter }}"
            - port: "{{ .Values.ports.controllerManager }}"
            - port: "{{ .Values.ports.scheduler }}"
            - port: "{{ .Values.ports.proxy }}"
            - port: "{{ .Values.ports.etcd }}"
