---
# Allow Tempo ingress from Alloy for trace ingestion
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tempo-ingress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: tempo
  ingress:
    # Allow OTLP traces from Alloy DaemonSet
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: alloy
      toPorts:
        - ports:
            - port: "{{ .Values.ports.tempo.otlpGrpc }}"
              protocol: TCP
            - port: "{{ .Values.ports.tempo.otlpHttp }}"
              protocol: TCP
    # Allow Grafana to query traces
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana
      toPorts:
        - ports:
            - port: "{{ .Values.ports.tempo.http }}"
              protocol: TCP
    # Allow Prometheus to scrape metrics
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.tempo.http }}"
              protocol: TCP
    # Allow from host for port-forwarding
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "{{ .Values.ports.tempo.http }}"
              protocol: TCP
            - port: "{{ .Values.ports.tempo.otlpGrpc }}"
              protocol: TCP
            - port: "{{ .Values.ports.tempo.otlpHttp }}"
              protocol: TCP
---
# Allow Tempo egress for DNS and API server
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tempo-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: tempo
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "{{ .Values.ports.dns }}"
              protocol: UDP
    # Allow API server access (for configmap/secret access)
    - toEntities:
        - kube-apiserver
