---
# Tempo network policy - ingress and egress
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tempo
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: tempo
  ingress:
    # Allow OTLP traces from Alloy DaemonSet
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: alloy
      toPorts:
        - ports:
            - port: "{{ .Values.ports.tempo.otlpGrpc }}"
              protocol: TCP
            - port: "{{ .Values.ports.tempo.otlpHttp }}"
              protocol: TCP
    # Allow Grafana to query traces
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana
      toPorts:
        - ports:
            - port: "{{ .Values.ports.tempo.http }}"
              protocol: TCP
    # Allow Prometheus to scrape metrics
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.tempo.http }}"
              protocol: TCP
    # Allow from host for port-forwarding
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "{{ .Values.ports.tempo.http }}"
              protocol: TCP
            - port: "{{ .Values.ports.tempo.otlpGrpc }}"
              protocol: TCP
            - port: "{{ .Values.ports.tempo.otlpHttp }}"
              protocol: TCP
  egress:
    # Allow API server access (for configmap/secret access)
    - toEntities:
        - kube-apiserver
