apiVersion: v2
name: kafka-ui
description: Provectus Kafka UI - Web interface for Apache Kafka management
version: 1.0.0
dependencies:
  - name: kafka-ui
    version: "0.7.6"
    repository: "https://provectus.github.io/kafka-ui-charts"
