---
# Argo Rollouts Controller Network Policy
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argo-rollouts-controller
  namespace: {{ .Release.Namespace }}
spec:
  description: "Argo Rollouts controller network policy"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts

  ingress:
    # Allow Prometheus to scrape metrics
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.ports.argoRollouts.metrics }}"
              protocol: TCP
