apiVersion: v2
name: kyverno-policies
description: Kyverno Pod Security Standards and Best Practices Policies
version: 1.0.0
dependencies:
  - name: kyverno-policies
    version: "3.6.2"
    repository: "https://kyverno.github.io/kyverno/"
