apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: juice-shop
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: https
  hostnames:
    - "juice-shop.localhost"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: juice-shop-stable
          port: {{ .Values.ports.httpService }}
          weight: 100
        - name: juice-shop-canary
          port: {{ .Values.ports.httpService }}
          weight: 0
