apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: juice-shop
  labels:
    app: juice-shop
    app.kubernetes.io/name: juice-shop
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
        app.kubernetes.io/name: juice-shop
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: juice-shop
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.ports.juiceShop }}
              name: http
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.juiceShop }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.juiceShop }}
            initialDelaySeconds: 5
            periodSeconds: 5
  strategy:
    canary:
      canaryService: juice-shop-canary
      stableService: juice-shop-stable
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: juice-shop
            namespace: {{ .Release.Namespace }}
      steps:
        - setWeight: 20
        - pause: {duration: 30s}
        - analysis:
            templates:
              - templateName: juice-shop-success-rate
        - setWeight: 50
        - pause: {duration: 30s}
        - analysis:
            templates:
              - templateName: juice-shop-success-rate
        - setWeight: 100
