apiVersion: v1
kind: Service
metadata:
  name: juice-shop-canary
  labels:
    app: juice-shop
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.httpService }}
      targetPort: {{ .Values.ports.juiceShop }}
      protocol: TCP
      name: http
  selector:
    app: juice-shop
