{{- if .Values.alertmanagerSlackSecrets.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhooks
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    slack-critical-webhook: {{ .Values.alertmanagerSlackSecrets.criticalWebhookEncrypted | quote }}
    slack-warning-webhook: {{ .Values.alertmanagerSlackSecrets.warningWebhookEncrypted | quote }}
  template:
    metadata:
      name: alertmanager-slack-webhooks
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
