{{- if .Values.vaultSecrets.enabled }}
---
# VaultAuth for monitoring namespace
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: monitoring-vault-auth
  namespace: {{ .Release.Namespace }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: default
  vaultConnectionRef: default
---
# Grafana admin credentials from Vault
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: secret
  path: monitoring/grafana
  destination:
    name: grafana-admin-credentials
    create: true
    labels:
      app.kubernetes.io/name: grafana
    transformation:
      excludeRaw: true
      templates:
        admin-user:
          text: '{{ `{{ .Secrets.admin-user }}` }}'
        admin-password:
          text: '{{ `{{ .Secrets.admin-password }}` }}'
  refreshAfter: 1h
  vaultAuthRef: monitoring-vault-auth
---
# Alertmanager Slack webhooks from Vault
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: alertmanager-slack-webhooks
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: secret
  path: monitoring/alertmanager
  destination:
    name: alertmanager-slack-webhooks
    create: true
    labels:
      app.kubernetes.io/name: alertmanager
    transformation:
      excludeRaw: true
      templates:
        slack-critical-webhook:
          text: '{{ `{{ .Secrets.slack-critical-webhook }}` }}'
        slack-warning-webhook:
          text: '{{ `{{ .Secrets.slack-warning-webhook }}` }}'
  refreshAfter: 1h
  vaultAuthRef: monitoring-vault-auth
{{- end }}
