apiVersion: v2
name: kyverno
description: Kyverno Kubernetes Native Policy Management
version: 1.0.0
dependencies:
  - name: kyverno
    version: "3.6.2"
    repository: "https://kyverno.github.io/kyverno/"
