apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-echo-success-rate
spec:
  args:
    - name: service-name
      value: http-echo-canary
  metrics:
    - name: success-rate
      interval: 30s
      count: 3
      successCondition: result[0] >= 0.95
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus-operated.monitoring:{{ .Values.ports.prometheus }}
          query: |
            sum(rate(
              envoy_cluster_upstream_rq{
                envoy_cluster_name=~".*http-echo-canary.*",
                envoy_response_code!~"5.*"
              }[1m]
            )) /
            sum(rate(
              envoy_cluster_upstream_rq{
                envoy_cluster_name=~".*http-echo-canary.*"
              }[1m]
            ))
