apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "http-echo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "http-echo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "http-echo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -text={{ .Values.text }}
          ports:
            - containerPort: {{ .Values.port }}
