---
# Allow ingress to http-echo from Gateway (Cilium Gateway uses ingress identity)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-from-gateway
spec:
  endpointSelector:
    matchLabels:
      app: http-echo
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "{{ .Values.ports.httpEcho }}"
              protocol: TCP
