apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-echo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
  selector:
    {{- include "http-echo.selectorLabels" . | nindent 4 }}
