apiVersion: v1
kind: Service
metadata:
  name: http-echo-canary
spec:
  ports:
    - port: {{ .Values.ports.httpService }}
      targetPort: {{ .Values.ports.httpEcho }}
  selector:
    app: http-echo
