apiVersion: v2
name: argocd
description: ArgoCD GitOps continuous delivery for Kubernetes
version: 1.0.0
dependencies:
  - name: argo-cd
    version: "9.4.1"
    repository: "https://argoproj.github.io/argo-helm"
