{{- range .Values.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "argocd.labels" $ | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .encryptedData }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ .name }}
      namespace: {{ $.Release.Namespace }}
    type: {{ .type | default "Opaque" }}
{{- end }}
