{{- if .Values.vaultSecrets.enabled }}
---
# VaultAuth for argocd namespace
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: argocd-vault-auth
  namespace: {{ .Release.Namespace }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: default
  vaultConnectionRef: vault-secrets-operator/default
---
# ArgoCD repository credentials from Vault
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-creds
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: secret
  path: argocd/repo-creds
  destination:
    name: argocd-repo-creds
    create: true
    labels:
      argocd.argoproj.io/secret-type: repo-creds
    transformation:
      excludeRaw: true
      templates:
        type:
          text: '{{ `{{ .Secrets.type }}` }}'
        url:
          text: '{{ `{{ .Secrets.url }}` }}'
        sshPrivateKey:
          text: '{{ `{{ .Secrets.sshPrivateKey }}` }}'
  refreshAfter: 1h
  vaultAuthRef: argocd-vault-auth
{{- end }}
